// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "LocaleLayout": {
      "title": "Welcome",
      "description": "This is the homepage"
    },
    "LocaleSwitcher": {
      "label": "Change language",
      "locale": "{locale, select, ru {RU} en {EN} other {Unknown}}"
    },
      "collections": {
        "title": "Our Collections",
        "seeCollection": "View Collection",
        "rings": "Rings",
        "earrings": "Earrings",
        "necklaces": "Necklaces",
        "bracelets": "Bracelets",
        "backToCollections": "Back to collections"
      }
    
  };
export default messages;